### ISSUE TITLE
Possiblity to disable auto locking task on exception?

### ISSUE THREAD

**Issue by mrvnklm** [J-Mose/CommandSchedulerBundle#111]
Hey, as I run some commands that might throw an exception, they shouldn't be locked. Is there a way to solve that?

**Comment by chrisjohnson00** [comment]
Check the docs, there's a lock timeout.  When you set this value it says "ignore the lock after this amount of time"

```
jmose_command_scheduler:

    # Default directory where scheduler will write output files
    #  This default value assume that php bin/console is launched from project's root and that the directory is writable
    # if log_path is set to false, logging to files is disabled at all 
    log_path: "%kernel.logs_dir%"
    # This default value disables timeout checking (see monitoring), set to a numeric value (seconds) to enable it
    lock_timeout: false
```
