### ISSUE TITLE
String could not be parsed as XML

### ISSUE THREAD

**Issue by kaloqndamqnov** [J-Mose/CommandSchedulerBundle#113]
Symfony 3.4
`/command-scheduler/detail/new`

After i try to add first scheduled command.

DEBUG 11:13:27 | event | Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand".
-- | -- | --
ERROR 11:13:27 | console | Error thrown while running command "list --format=xml". Message: "Warning: DOMDocument::createTextNode() expects parameter 1 to be string, object given"
DEBUG 11:13:27 | event | Notified event "console.error" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onException".
DEBUG 11:13:27 | event | Notified event "console.error" to listener "Symfony\Component\Console\EventListener\ErrorListener::onConsoleError".
DEBUG 11:13:27 | console | Command "list --format=xml" exited with code "1"
DEBUG 11:13:27 | event | Notified event "console.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate".
DEBUG 11:13:27 | event | Notified event "console.terminate" to listener "Symfony\Component\Console\EventListener\ErrorListener::onConsoleTerminate".
DEBUG 11:13:27 | event | Notified event "console.terminate" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onTerminate".
CRITICAL 11:13:27 | request | Uncaught PHP Exception Exception: "String could not be parsed as XML" at /var/www/symfony/vendor/jmose/command-scheduler-bundle/Service/CommandParser.php line 74
DEBUG 11:13:27 | event | Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".

`
![image](https://user-images.githubusercontent.com/26900282/46345758-663fb500-c64e-11e8-94d3-0c2ca465c17f.png)

AppKernel:
 ` new JMose\CommandSchedulerBundle\JMoseCommandSchedulerBundle(),`
Routing:
```
jmose_command_scheduler:
  resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
  prefix:   /

```
Config:
```

jmose_command_scheduler:

  # Default directory where scheduler will write output files
  #  This default value assume that php bin/console is launched from project's root and that the directory is writable
  # if log_path is set to false, logging to files is disabled at all
  log_path: "%kernel.root_dir%/../scheduler/log"
  # This default value disables timeout checking (see monitoring), set to a numeric value (seconds) to enable it
#  lock_timeout: false
  # receivers for reporting mails
#  monitor_mail: []
  # set a custom subject for monitor mails (first placeholder will be replaced by the hostname, second by the date)
#  monitor_mail_subject: cronjob monitoring %s, %s
  # to send "everything's all right" emails to receivers for reporting mails set this value to "true" (see monitoring)
#  send_ok: false

  # Namespaces listed here won't be listed in the list
  excluded_command_namespaces:
  - _global
  - scheduler
  - server
  - container
  - config
  - generate
  - init
  - router

  # Doctrine manager
#  doctrine_manager: default
```
Composer:
`"jmose/command-scheduler-bundle": "2.0.0",`
